<?php 
/**
 * Cronjob Scheduler Include File
 *
 * This page allows you to create Cronjob Scheduler custom actions
 * through the WordPress admin. Actions can also be created within
 * theme files or other PHP files throughout your WordPress install.
 *
 * Do not edit this file unless you have a good understanding of PHP, 
 * saving this with invalid code can render your WordPress install inoperable
 * until you can fix the issue using FTP or another file editing utility.
**/

function automail () 
{
      global $wpdb, $table_prefix;
      $result = $wpdb->get_results("Select * from ".$table_prefix."calendar");
      foreach($result as $row)
      {
            $eid = $row->event_id;
            $etitle = $row->event_title;
            $evenue =$row->event_venue;
            $edesc = $row->event_desc;
            $evenue =$row->event_venue;
            $begin = $row->event_begin;
            $end = $row->event_end;
            $etime = $row->event_time;
            $tdate = date('Y-m-d');
            $ctime = date('H:i');
            $date = date('H:i');            
            $start = $begin." ".$etime;
            $currentDate = strtotime($start);
            $futureDate = $currentDate-(60*30);
            $formatDate = date("H:i", $futureDate);
            $mtime = date('H:i a', strtotime($etime));
            if($begin == $tdate)
            {
                  if($date == $formatDate)
                  {
                             $result1 = $wpdb->get_results("Select * from ".$table_prefix."event_users where Eve_id = '$eid' AND Accepted = '0' AND Declined = '1'");
                              foreach($result1 as $row1)
                              {
                                    $uid = $row1-->$Eve_User_Id;
                                    $result2 = $wpdb->get_row("Select * from ".$table_prefix."users where ID= '$uid'");
                                    $to = $result2->user_email;
                                    $subject = 'Event Remainder';
                                    $message = '
                                    <div id="email_container" style="background:#444">
                                          <div style="width:570px; padding:0 0 0 20px; margin:50px auto 12px auto" id="email_header">
                                                <span style="background:#585858; color:#fff; padding:12px;font-family:trebuchet ms; letter-spacing:1px; 
                                                -moz-border-radius-topleft:5px; -webkit-border-top-left-radius:5px; 
                                                border-top-left-radius:5px;moz-border-radius-topright:5px; -webkit-border-top-right-radius:5px; 
                                                border-top-right-radius:5px;">
                                                Event Remainder</div>
                                          </div>
                                          <div style="width:550px; padding:0 20px 20px 20px; background:#fff; margin:0 auto; border:3px #000 solid;
                                                moz-border-radius:5px; -webkit-border-radius:5px; border-radius:5px; color:#454545;line-height:1.5em; " id="email_content">

                                                <h1 style="padding:5px 0 0 0; font-family:georgia;font-weight:500;font-size:24px;color:#000;border-bottom:1px solid #bbb">
                                                      This is the remainder  for '.$etitle.'.
                                                </h1>

                                                <p>
                                                      Related informations <br/>Venue: '
                                                      .$evenue.'<br/>Event Starts at: '.$begin.' '.$mtime.'<br/>Event ends at: '.$end.'<br/>Event description: '.$edesc.'
                                                </p>
                                                 				
                                          </div>
                                    </div>';
                                    $headers= "MIME-Version: 1.0\n" ."Content-Type: text/html; charset=\"" . get_option('blog_charset') . "\"\n";
                                    wp_mail($to, $subject, $message, $headers);
                              }
                  }
                  //echo '<script>alert("'.$formatDate.' '.$date.'")</script>';
            }
      }
} 
add_action('automail', 'automail');
